### ISSUE TITLE
server crashed when nothing happened (instantly)

### ISSUE THREAD

**Issue by ghost** [Fungie2134/AuthMod#8] opened 2017-06-20 08:48 UTC
[crash.txt](https://github.com/Fungie2134/AuthMod/files/1087521/crash.txt)
please help aang :(

**Comment by ghost** [comment] 2017-06-20 08:49
and you can visit our server again, it's the modpack Tekxit 3: Magenji. for test or etc.. server is open..

**Comment by Aang23** [comment] 2017-06-20 09:04
Can I have the crash report ? And the log ?

**Comment by ghost** [comment] 2017-06-20 09:04
you already have it in the report

**Comment by ghost** [comment] 2017-06-20 09:18
[2017-06-20-1.log.gz](https://github.com/Fungie2134/AuthMod/files/1087618/2017-06-20-1.log.gz)

**Comment by ghost** [comment] 2017-06-20 09:18
and here is the logs

**Comment by ghost** [comment] 2017-06-20 09:36
hey ah, it happened again. me and my friend were in the server, nobody joined or logged out and this crash happened again.

**Comment by Aang23** [comment] 2017-06-20 16:00
Can you try without BetterCombat ? I may come from a incompatibility which I can fix, but I want to be sure.

**Comment by ghost** [comment] 2017-06-20 18:40
uhm, we jumped to 1.12. i will tell you if it happens again. (soon)

**Comment by ghost** [comment] 2017-06-20 18:49
btw, theres no better combat mod for 1.12.

**Comment by Aang23** [comment] 2017-06-20 19:32
Ok, if I happen again I will try to reproduce it. Never got this bug... 

They are updating it, it may be released soon.

**Comment by Aang23** [comment] 2017-06-20 19:42
Else it may come from the IP logging, a mod ( BetterCombat ? ) set the IP to null before my mod could get it...

**Comment by ghost** [comment] 2017-06-20 19:43
yes, i updated your mod. i will tell you if anything happens dont worry.

**Comment by ghost** [comment] 2017-06-20 19:56
heyy ah, it crashed again (with the newest version of authmod) please help
[crash.txt](https://github.com/Fungie2134/AuthMod/files/1089509/crash.txt)

**Comment by ghost** [comment] 2017-06-20 20:05
[secondc.txt](https://github.com/Fungie2134/AuthMod/files/1089544/secondc.txt)
here is just another one

**Comment by Aang23** [comment] 2017-06-20 20:05
I know what happen, fix out tomorrow, just use the first 1.12 build during the fix.

**Comment by ghost** [comment] 2017-06-20 20:07
okay

**Comment by Aang23** [comment] 2017-06-20 20:09
I am sure it is an incompatibility with another mod, which one I do not know right now, but I know how to fix it, do you want me to send the build on Discord before curse?

**Comment by ghost** [comment] 2017-06-20 20:15
yes, of course. i always welcome you on our discord, such as anybody.

**Comment by ghost** [comment] 2017-06-20 20:16
hmm so i should close this :D

**Comment by Aang23** [comment] 2017-06-20 20:27
I will reopen if needed, we never know :D

**Comment by ghost** [comment] 2017-06-20 20:32
oh sorry i wrote to wrong issue. i was going to close this one https://github.com/McJty/TheOneProbe/issues/175#issuecomment-309877817
lol

**Comment by Aang23** [comment] 2017-06-26 11:32
Should be fixed now !

**Comment by Fungie2134** [comment] 2017-07-23 13:15
Reopened because there might be some incompatibilities which may cause crashes.

**Closed as completed** 2017-07-23 13:15 UTC
Labels: Compatibility, Fixed? - Testing
