### ISSUE TITLE
Mechanical Users or other blocks that simulate user input don't work

### ISSUE THREAD

**Issue by fucnknown** [Fungie2134/AuthMod#9] opened 2017-06-26 00:58 UTC
Mechanical User from Extra Utilities 2 doesn't work at all with AuthMod working,

I suppose it's related to the way this mods "simulate" a player to allow it to activate items.

Issue dissapeared by simply removing AuthMod.

**Comment by Aang23** [comment] 2017-06-26 11:35
I have Extra Utilities on my server and I'm going to try.
I'm working on a debug mode which may be activated for fixing this kind of things...
This is a fakeplayer, I did not check how it work in this mod.

Thanks for reporting !

**Comment by ProgrammedSoul** [comment] 2017-07-02 23:39
Same issue here. None of my machines on the server can break block, place block or auto use, in my case it is Actually Addition block/fluid breaker/placer and vertical miner, someone reports IC2 miner, Railcraft boring machine, Refined Storage(and AE2) Annihilation Plane also does not work... It looks like Authmod are asking those fake players from those modes to log in, and of course they won't, so they are prevented from doing anything......

**Comment by Aang23** [comment] 2017-07-08 09:10
I'm correcting this. The problem is exactly what you explained. Fake players also calls EntityPlayer Event, so my mod recognize them as real player and ask them to login. The only way to make this compatible is to add an UUID / Username exception for most common mods, and a config file for others one.

**Comment by Aang23** [comment] 2017-07-12 11:21
Fixed in 2.6 ! 
I only added 2 of them presently. Please ask if you need more...
I am trying all the ones I can to find and add them. A little tutorial to add you own is being redacted!

**Closed as completed** 2017-07-12 11:21 UTC
Labels: Bug, Fixed, Compatibility
